# Compiles and tests the solutions to week 8 lab exercises.

CC=gcc
CFLAGS=-Wall -ansi

all:		adjacent-sum

adjacent-sum:	adjacent-sum.o
	$(CC) $(CFLAGS) -o adjacent-sum adjacent-sum.o


.PHONY:		all

# vim: ts=8 sw=4 noet
