# Compiles and tests the solutions to week 3 lab exercises.
#
# To run this, type "make bed" in your terminal.

graph:		graph.c
	gcc -Wall -ansi -o graph graph.c

nextprime:	nextprime.c
	gcc -Wall -ansi -o nextprime nextprime.c

ascii_table:	ascii_table.c
	gcc -Wall -ansi -o ascii_table ascii_table.c


bed:		graph nextprime ascii_table


.PHONY:		bed

# vim: ts=8 sw=4 noet
