# Compiles and tests the solutions to week 3 lab exercises.
#
# To run this, type "make it so" in your terminal.

graph:		graph.c
	gcc -Wall -ansi -o graph graph.c


bed:		graph


.PHONY:		bed

# vim: ts=8 sw=4 noet
