# Compiles and tests the solutions to week 5 lab exercises.
#
# To run this, type "make me a sandwich" in your terminal.

CC=gcc
CFLAGS=-Wall -ansi

perfect:	perfect.o
	$(CC) $(CFLAGS) -o perfect perfect.o

me a:

sandwich:	perfect 


.PHONY:		me a sandwich

# vim: ts=8 sw=4 noet
